changelog:
  categories:
    - title: Bugfixes
      labels:
        - bug
    - title: New Additions
      labels:
        - enhancement
    - title: Reports
      labels:
        - reports
    - title: Other Changes
      labels:
        - "*"
