// <auto-generated />
using System;
using FHHL.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FHHL.Data.Migrations
{
    [DbContext(typeof(FHHLDbContext))]
    [Migration("20210114195411_jesse1")]
    partial class jesse1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("FHHL.Data.DomainModels.Assignee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityColumn();

                    b.Property<bool>("ActiveFlag")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("AddDateTimeOffset")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("AddUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset?>("ChgDateTimeOffset")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("ChgUser")
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset?>("DelDateTimeOffset")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<bool>("DelFlag")
                        .HasColumnType("bit");

                    b.Property<string>("DelUser")
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.ToTable("Assignees");
                });

            modelBuilder.Entity("FHHL.Data.DomainModels.PregnancyState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityColumn();

                    b.Property<bool>("ActiveFlag")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("AddDateTimeOffset")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("AddUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset?>("ChgDateTimeOffset")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("ChgUser")
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset?>("DelDateTimeOffset")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<bool>("DelFlag")
                        .HasColumnType("bit");

                    b.Property<string>("DelUser")
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.ToTable("PregnancyStates");
                });

            modelBuilder.Entity("FHHL.Data.DomainModels.Program", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityColumn();

                    b.Property<bool>("ActiveFlag")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("AddDateTimeOffset")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("AddUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset?>("ChgDateTimeOffset")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("ChgUser")
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset?>("DelDateTimeOffset")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<bool>("DelFlag")
                        .HasColumnType("bit");

                    b.Property<string>("DelUser")
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.ToTable("Programs");
                });

            modelBuilder.Entity("FHHL.Data.DomainModels.Race", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityColumn();

                    b.Property<bool>("ActiveFlag")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("AddDateTimeOffset")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("AddUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset?>("ChgDateTimeOffset")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("ChgUser")
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset?>("DelDateTimeOffset")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<bool>("DelFlag")
                        .HasColumnType("bit");

                    b.Property<string>("DelUser")
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.ToTable("Races");
                });

            modelBuilder.Entity("FHHL.Data.DomainModels.ReferralSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityColumn();

                    b.Property<bool>("ActiveFlag")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("AddDateTimeOffset")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("AddUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset?>("ChgDateTimeOffset")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("ChgUser")
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset?>("DelDateTimeOffset")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<bool>("DelFlag")
                        .HasColumnType("bit");

                    b.Property<string>("DelUser")
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.ToTable("ReferralSources");
                });

            modelBuilder.Entity("FHHL.Data.DomainModels.RiskLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityColumn();

                    b.Property<bool>("ActiveFlag")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("AddDateTimeOffset")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("AddUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset?>("ChgDateTimeOffset")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("ChgUser")
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset?>("DelDateTimeOffset")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<bool>("DelFlag")
                        .HasColumnType("bit");

                    b.Property<string>("DelUser")
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.ToTable("RiskLevels");
                });

            modelBuilder.Entity("FHHL.Data.DomainModels.VisitResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityColumn();

                    b.Property<bool>("ActiveFlag")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("AddDateTimeOffset")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("AddUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset?>("ChgDateTimeOffset")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("ChgUser")
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset?>("DelDateTimeOffset")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<bool>("DelFlag")
                        .HasColumnType("bit");

                    b.Property<string>("DelUser")
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.ToTable("VisitResults");
                });
#pragma warning restore 612, 618
        }
    }
}
