// <auto-generated />
using System;
using FHHL.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FHHL.Data.Migrations
{
    [DbContext(typeof(FHHLDbContext))]
    [Migration("20210316181649_jesse7")]
    partial class jesse7
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("FHHL.Data.DomainModels.Assignee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityColumn();

                    b.Property<bool>("ActiveFlag")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("AddDateTimeOffset")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("AddUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset?>("ChgDateTimeOffset")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("ChgUser")
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset?>("DelDateTimeOffset")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<bool>("DelFlag")
                        .HasColumnType("bit");

                    b.Property<string>("DelUser")
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.ToTable("Assignees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActiveFlag = true,
                            AddDateTimeOffset = new DateTimeOffset(new DateTime(2021, 3, 16, 13, 16, 48, 528, DateTimeKind.Unspecified).AddTicks(104), new TimeSpan(0, -5, 0, 0, 0)),
                            AddUser = "Seed",
                            DelFlag = false,
                            Label = "Teresa"
                        },
                        new
                        {
                            Id = 2,
                            ActiveFlag = true,
                            AddDateTimeOffset = new DateTimeOffset(new DateTime(2021, 3, 16, 13, 16, 48, 530, DateTimeKind.Unspecified).AddTicks(677), new TimeSpan(0, -5, 0, 0, 0)),
                            AddUser = "Seed",
                            DelFlag = false,
                            Label = "Bonnie"
                        },
                        new
                        {
                            Id = 3,
                            ActiveFlag = true,
                            AddDateTimeOffset = new DateTimeOffset(new DateTime(2021, 3, 16, 13, 16, 48, 530, DateTimeKind.Unspecified).AddTicks(737), new TimeSpan(0, -5, 0, 0, 0)),
                            AddUser = "Seed",
                            DelFlag = false,
                            Label = "Missy"
                        },
                        new
                        {
                            Id = 4,
                            ActiveFlag = true,
                            AddDateTimeOffset = new DateTimeOffset(new DateTime(2021, 3, 16, 13, 16, 48, 530, DateTimeKind.Unspecified).AddTicks(746), new TimeSpan(0, -5, 0, 0, 0)),
                            AddUser = "Seed",
                            DelFlag = false,
                            Label = "Marla"
                        },
                        new
                        {
                            Id = 5,
                            ActiveFlag = true,
                            AddDateTimeOffset = new DateTimeOffset(new DateTime(2021, 3, 16, 13, 16, 48, 530, DateTimeKind.Unspecified).AddTicks(753), new TimeSpan(0, -5, 0, 0, 0)),
                            AddUser = "Seed",
                            DelFlag = false,
                            Label = "Ariona"
                        },
                        new
                        {
                            Id = 6,
                            ActiveFlag = true,
                            AddDateTimeOffset = new DateTimeOffset(new DateTime(2021, 3, 16, 13, 16, 48, 530, DateTimeKind.Unspecified).AddTicks(759), new TimeSpan(0, -5, 0, 0, 0)),
                            AddUser = "Seed",
                            DelFlag = false,
                            Label = "Outreach Letter"
                        },
                        new
                        {
                            Id = 7,
                            ActiveFlag = true,
                            AddDateTimeOffset = new DateTimeOffset(new DateTime(2021, 3, 16, 13, 16, 48, 530, DateTimeKind.Unspecified).AddTicks(765), new TimeSpan(0, -5, 0, 0, 0)),
                            AddUser = "Seed",
                            DelFlag = false,
                            Label = "Felica"
                        },
                        new
                        {
                            Id = 8,
                            ActiveFlag = true,
                            AddDateTimeOffset = new DateTimeOffset(new DateTime(2021, 3, 16, 13, 16, 48, 530, DateTimeKind.Unspecified).AddTicks(771), new TimeSpan(0, -5, 0, 0, 0)),
                            AddUser = "Seed",
                            DelFlag = false,
                            Label = "Jene"
                        },
                        new
                        {
                            Id = 9,
                            ActiveFlag = true,
                            AddDateTimeOffset = new DateTimeOffset(new DateTime(2021, 3, 16, 13, 16, 48, 530, DateTimeKind.Unspecified).AddTicks(778), new TimeSpan(0, -5, 0, 0, 0)),
                            AddUser = "Seed",
                            DelFlag = false,
                            Label = "Abby"
                        },
                        new
                        {
                            Id = 10,
                            ActiveFlag = true,
                            AddDateTimeOffset = new DateTimeOffset(new DateTime(2021, 3, 16, 13, 16, 48, 530, DateTimeKind.Unspecified).AddTicks(784), new TimeSpan(0, -5, 0, 0, 0)),
                            AddUser = "Seed",
                            DelFlag = false,
                            Label = "Tandem"
                        },
                        new
                        {
                            Id = 11,
                            ActiveFlag = true,
                            AddDateTimeOffset = new DateTimeOffset(new DateTime(2021, 3, 16, 13, 16, 48, 530, DateTimeKind.Unspecified).AddTicks(790), new TimeSpan(0, -5, 0, 0, 0)),
                            AddUser = "Seed",
                            DelFlag = false,
                            Label = "Renee"
                        },
                        new
                        {
                            Id = 12,
                            ActiveFlag = true,
                            AddDateTimeOffset = new DateTimeOffset(new DateTime(2021, 3, 16, 13, 16, 48, 530, DateTimeKind.Unspecified).AddTicks(796), new TimeSpan(0, -5, 0, 0, 0)),
                            AddUser = "Seed",
                            DelFlag = false,
                            Label = "Emma"
                        },
                        new
                        {
                            Id = 13,
                            ActiveFlag = true,
                            AddDateTimeOffset = new DateTimeOffset(new DateTime(2021, 3, 16, 13, 16, 48, 530, DateTimeKind.Unspecified).AddTicks(802), new TimeSpan(0, -5, 0, 0, 0)),
                            AddUser = "Seed",
                            DelFlag = false,
                            Label = "Marsue"
                        });
                });

            modelBuilder.Entity("FHHL.Data.DomainModels.Caregiver", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityColumn();

                    b.Property<DateTimeOffset?>("AddDateTimeOffset")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("AddUser")
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset?>("ChgDateTimeOffset")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("ChgUser")
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset?>("DateOfBirth")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<DateTimeOffset?>("DelDateTimeOffset")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<bool>("DelFlag")
                        .HasColumnType("bit");

                    b.Property<string>("DelUser")
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("Foster")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("MomClass")
                        .HasColumnType("bit");

                    b.Property<bool>("Spanish")
                        .HasColumnType("bit");

                    b.Property<string>("Zip")
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.ToTable("Caregivers");
                });

            modelBuilder.Entity("FHHL.Data.DomainModels.CaregiverRace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityColumn();

                    b.Property<int>("CaregiverId")
                        .HasColumnType("integer");

                    b.Property<int>("RaceId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("CaregiverRaces");
                });

            modelBuilder.Entity("FHHL.Data.DomainModels.PregnancyState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityColumn();

                    b.Property<bool>("ActiveFlag")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("AddDateTimeOffset")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("AddUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset?>("ChgDateTimeOffset")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("ChgUser")
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset?>("DelDateTimeOffset")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<bool>("DelFlag")
                        .HasColumnType("bit");

                    b.Property<string>("DelUser")
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.ToTable("PregnancyStates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActiveFlag = true,
                            AddDateTimeOffset = new DateTimeOffset(new DateTime(2021, 3, 16, 13, 16, 48, 531, DateTimeKind.Unspecified).AddTicks(1142), new TimeSpan(0, -5, 0, 0, 0)),
                            AddUser = "Seed",
                            DelFlag = false,
                            Label = "Prebirth"
                        },
                        new
                        {
                            Id = 2,
                            ActiveFlag = true,
                            AddDateTimeOffset = new DateTimeOffset(new DateTime(2021, 3, 16, 13, 16, 48, 531, DateTimeKind.Unspecified).AddTicks(2293), new TimeSpan(0, -5, 0, 0, 0)),
                            AddUser = "Seed",
                            DelFlag = false,
                            Label = "Birth"
                        },
                        new
                        {
                            Id = 3,
                            ActiveFlag = true,
                            AddDateTimeOffset = new DateTimeOffset(new DateTime(2021, 3, 16, 13, 16, 48, 531, DateTimeKind.Unspecified).AddTicks(2338), new TimeSpan(0, -5, 0, 0, 0)),
                            AddUser = "Seed",
                            DelFlag = false,
                            Label = "Toddler"
                        },
                        new
                        {
                            Id = 4,
                            ActiveFlag = true,
                            AddDateTimeOffset = new DateTimeOffset(new DateTime(2021, 3, 16, 13, 16, 48, 531, DateTimeKind.Unspecified).AddTicks(2345), new TimeSpan(0, -5, 0, 0, 0)),
                            AddUser = "Seed",
                            DelFlag = false,
                            Label = "Infant"
                        },
                        new
                        {
                            Id = 5,
                            ActiveFlag = true,
                            AddDateTimeOffset = new DateTimeOffset(new DateTime(2021, 3, 16, 13, 16, 48, 531, DateTimeKind.Unspecified).AddTicks(2351), new TimeSpan(0, -5, 0, 0, 0)),
                            AddUser = "Seed",
                            DelFlag = false,
                            Label = "Postpartum"
                        });
                });

            modelBuilder.Entity("FHHL.Data.DomainModels.Program", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityColumn();

                    b.Property<bool>("ActiveFlag")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("AddDateTimeOffset")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("AddUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset?>("ChgDateTimeOffset")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("ChgUser")
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset?>("DelDateTimeOffset")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<bool>("DelFlag")
                        .HasColumnType("bit");

                    b.Property<string>("DelUser")
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.ToTable("Programs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActiveFlag = true,
                            AddDateTimeOffset = new DateTimeOffset(new DateTime(2021, 3, 16, 13, 16, 48, 531, DateTimeKind.Unspecified).AddTicks(3335), new TimeSpan(0, -5, 0, 0, 0)),
                            AddUser = "Seed",
                            DelFlag = false,
                            Label = "HSHV"
                        },
                        new
                        {
                            Id = 2,
                            ActiveFlag = true,
                            AddDateTimeOffset = new DateTimeOffset(new DateTime(2021, 3, 16, 13, 16, 48, 531, DateTimeKind.Unspecified).AddTicks(4477), new TimeSpan(0, -5, 0, 0, 0)),
                            AddUser = "Seed",
                            DelFlag = false,
                            Label = "NBHV"
                        },
                        new
                        {
                            Id = 3,
                            ActiveFlag = true,
                            AddDateTimeOffset = new DateTimeOffset(new DateTime(2021, 3, 16, 13, 16, 48, 531, DateTimeKind.Unspecified).AddTicks(4526), new TimeSpan(0, -5, 0, 0, 0)),
                            AddUser = "Seed",
                            DelFlag = false,
                            Label = "NFP"
                        },
                        new
                        {
                            Id = 4,
                            ActiveFlag = true,
                            AddDateTimeOffset = new DateTimeOffset(new DateTime(2021, 3, 16, 13, 16, 48, 531, DateTimeKind.Unspecified).AddTicks(4533), new TimeSpan(0, -5, 0, 0, 0)),
                            AddUser = "Seed",
                            DelFlag = false,
                            Label = "PHN"
                        },
                        new
                        {
                            Id = 5,
                            ActiveFlag = true,
                            AddDateTimeOffset = new DateTimeOffset(new DateTime(2021, 3, 16, 13, 16, 48, 531, DateTimeKind.Unspecified).AddTicks(4540), new TimeSpan(0, -5, 0, 0, 0)),
                            AddUser = "Seed",
                            DelFlag = false,
                            Label = "PART C"
                        },
                        new
                        {
                            Id = 6,
                            ActiveFlag = true,
                            AddDateTimeOffset = new DateTimeOffset(new DateTime(2021, 3, 16, 13, 16, 48, 531, DateTimeKind.Unspecified).AddTicks(4546), new TimeSpan(0, -5, 0, 0, 0)),
                            AddUser = "Seed",
                            DelFlag = false,
                            Label = "FS"
                        },
                        new
                        {
                            Id = 7,
                            ActiveFlag = true,
                            AddDateTimeOffset = new DateTimeOffset(new DateTime(2021, 3, 16, 13, 16, 48, 531, DateTimeKind.Unspecified).AddTicks(4552), new TimeSpan(0, -5, 0, 0, 0)),
                            AddUser = "Seed",
                            DelFlag = false,
                            Label = "Outreach"
                        });
                });

            modelBuilder.Entity("FHHL.Data.DomainModels.Race", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityColumn();

                    b.Property<bool>("ActiveFlag")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("AddDateTimeOffset")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("AddUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset?>("ChgDateTimeOffset")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("ChgUser")
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset?>("DelDateTimeOffset")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<bool>("DelFlag")
                        .HasColumnType("bit");

                    b.Property<string>("DelUser")
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.ToTable("Races");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActiveFlag = true,
                            AddDateTimeOffset = new DateTimeOffset(new DateTime(2021, 3, 16, 13, 16, 48, 531, DateTimeKind.Unspecified).AddTicks(5512), new TimeSpan(0, -5, 0, 0, 0)),
                            AddUser = "Seed",
                            DelFlag = false,
                            Label = "White"
                        },
                        new
                        {
                            Id = 2,
                            ActiveFlag = true,
                            AddDateTimeOffset = new DateTimeOffset(new DateTime(2021, 3, 16, 13, 16, 48, 531, DateTimeKind.Unspecified).AddTicks(6681), new TimeSpan(0, -5, 0, 0, 0)),
                            AddUser = "Seed",
                            DelFlag = false,
                            Label = "Black"
                        },
                        new
                        {
                            Id = 3,
                            ActiveFlag = true,
                            AddDateTimeOffset = new DateTimeOffset(new DateTime(2021, 3, 16, 13, 16, 48, 531, DateTimeKind.Unspecified).AddTicks(6723), new TimeSpan(0, -5, 0, 0, 0)),
                            AddUser = "Seed",
                            DelFlag = false,
                            Label = "Black/White"
                        },
                        new
                        {
                            Id = 4,
                            ActiveFlag = true,
                            AddDateTimeOffset = new DateTimeOffset(new DateTime(2021, 3, 16, 13, 16, 48, 531, DateTimeKind.Unspecified).AddTicks(6730), new TimeSpan(0, -5, 0, 0, 0)),
                            AddUser = "Seed",
                            DelFlag = false,
                            Label = "American Indian"
                        },
                        new
                        {
                            Id = 5,
                            ActiveFlag = true,
                            AddDateTimeOffset = new DateTimeOffset(new DateTime(2021, 3, 16, 13, 16, 48, 531, DateTimeKind.Unspecified).AddTicks(6736), new TimeSpan(0, -5, 0, 0, 0)),
                            AddUser = "Seed",
                            DelFlag = false,
                            Label = "Asian"
                        },
                        new
                        {
                            Id = 6,
                            ActiveFlag = true,
                            AddDateTimeOffset = new DateTimeOffset(new DateTime(2021, 3, 16, 13, 16, 48, 531, DateTimeKind.Unspecified).AddTicks(6742), new TimeSpan(0, -5, 0, 0, 0)),
                            AddUser = "Seed",
                            DelFlag = false,
                            Label = "Non-Hispanic"
                        },
                        new
                        {
                            Id = 7,
                            ActiveFlag = true,
                            AddDateTimeOffset = new DateTimeOffset(new DateTime(2021, 3, 16, 13, 16, 48, 531, DateTimeKind.Unspecified).AddTicks(6748), new TimeSpan(0, -5, 0, 0, 0)),
                            AddUser = "Seed",
                            DelFlag = false,
                            Label = "Unknown"
                        },
                        new
                        {
                            Id = 8,
                            ActiveFlag = true,
                            AddDateTimeOffset = new DateTimeOffset(new DateTime(2021, 3, 16, 13, 16, 48, 531, DateTimeKind.Unspecified).AddTicks(6754), new TimeSpan(0, -5, 0, 0, 0)),
                            AddUser = "Seed",
                            DelFlag = false,
                            Label = "Other"
                        });
                });

            modelBuilder.Entity("FHHL.Data.DomainModels.Referral", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityColumn();

                    b.Property<DateTimeOffset?>("AddDateTimeOffset")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("AddUser")
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset?>("AssignDate")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<int?>("AssignedTo")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("ChgDateTimeOffset")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("ChgUser")
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset?>("ChildDateOfBirth")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("ChildName")
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset?>("DelDateTimeOffset")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<bool>("DelFlag")
                        .HasColumnType("bit");

                    b.Property<string>("DelUser")
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset?>("EstimatedDeliveryDate")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<bool>("FirstChild")
                        .HasColumnType("bit");

                    b.Property<bool>("FtoF")
                        .HasColumnType("bit");

                    b.Property<int?>("LOR")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(256)");

                    b.Property<int?>("Program")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("ReferralDate")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("ReferralReason")
                        .HasColumnType("nvarchar(256)");

                    b.Property<int?>("Result")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("ResultDate")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<int?>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Referrals");
                });

            modelBuilder.Entity("FHHL.Data.DomainModels.ReferralRace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityColumn();

                    b.Property<int>("RaceId")
                        .HasColumnType("integer");

                    b.Property<int>("ReferralId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("ReferralRaces");
                });

            modelBuilder.Entity("FHHL.Data.DomainModels.ReferralReferralSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityColumn();

                    b.Property<int>("ReferralId")
                        .HasColumnType("integer");

                    b.Property<int>("ReferralSourceId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("ReferralReferralSources");
                });

            modelBuilder.Entity("FHHL.Data.DomainModels.ReferralSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityColumn();

                    b.Property<bool>("ActiveFlag")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("AddDateTimeOffset")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("AddUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset?>("ChgDateTimeOffset")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("ChgUser")
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset?>("DelDateTimeOffset")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<bool>("DelFlag")
                        .HasColumnType("bit");

                    b.Property<string>("DelUser")
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.ToTable("ReferralSources");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActiveFlag = true,
                            AddDateTimeOffset = new DateTimeOffset(new DateTime(2021, 3, 16, 13, 16, 48, 531, DateTimeKind.Unspecified).AddTicks(7807), new TimeSpan(0, -5, 0, 0, 0)),
                            AddUser = "Seed",
                            DelFlag = false,
                            Label = "PG Testing"
                        },
                        new
                        {
                            Id = 2,
                            ActiveFlag = true,
                            AddDateTimeOffset = new DateTimeOffset(new DateTime(2021, 3, 16, 13, 16, 48, 531, DateTimeKind.Unspecified).AddTicks(8910), new TimeSpan(0, -5, 0, 0, 0)),
                            AddUser = "Seed",
                            DelFlag = false,
                            Label = "M & I"
                        },
                        new
                        {
                            Id = 3,
                            ActiveFlag = true,
                            AddDateTimeOffset = new DateTimeOffset(new DateTime(2021, 3, 16, 13, 16, 48, 531, DateTimeKind.Unspecified).AddTicks(8964), new TimeSpan(0, -5, 0, 0, 0)),
                            AddUser = "Seed",
                            DelFlag = false,
                            Label = "Hopsital"
                        },
                        new
                        {
                            Id = 4,
                            ActiveFlag = true,
                            AddDateTimeOffset = new DateTimeOffset(new DateTime(2021, 3, 16, 13, 16, 48, 531, DateTimeKind.Unspecified).AddTicks(8971), new TimeSpan(0, -5, 0, 0, 0)),
                            AddUser = "Seed",
                            DelFlag = false,
                            Label = "WIC"
                        },
                        new
                        {
                            Id = 5,
                            ActiveFlag = true,
                            AddDateTimeOffset = new DateTimeOffset(new DateTime(2021, 3, 16, 13, 16, 48, 531, DateTimeKind.Unspecified).AddTicks(8978), new TimeSpan(0, -5, 0, 0, 0)),
                            AddUser = "Seed",
                            DelFlag = false,
                            Label = "Successful Connections"
                        },
                        new
                        {
                            Id = 6,
                            ActiveFlag = true,
                            AddDateTimeOffset = new DateTimeOffset(new DateTime(2021, 3, 16, 13, 16, 48, 531, DateTimeKind.Unspecified).AddTicks(8984), new TimeSpan(0, -5, 0, 0, 0)),
                            AddUser = "Seed",
                            DelFlag = false,
                            Label = "TARC"
                        },
                        new
                        {
                            Id = 7,
                            ActiveFlag = true,
                            AddDateTimeOffset = new DateTimeOffset(new DateTime(2021, 3, 16, 13, 16, 48, 531, DateTimeKind.Unspecified).AddTicks(8990), new TimeSpan(0, -5, 0, 0, 0)),
                            AddUser = "Seed",
                            DelFlag = false,
                            Label = "Washburn"
                        },
                        new
                        {
                            Id = 8,
                            ActiveFlag = true,
                            AddDateTimeOffset = new DateTimeOffset(new DateTime(2021, 3, 16, 13, 16, 48, 531, DateTimeKind.Unspecified).AddTicks(8996), new TimeSpan(0, -5, 0, 0, 0)),
                            AddUser = "Seed",
                            DelFlag = false,
                            Label = "Other"
                        },
                        new
                        {
                            Id = 9,
                            ActiveFlag = true,
                            AddDateTimeOffset = new DateTimeOffset(new DateTime(2021, 3, 16, 13, 16, 48, 531, DateTimeKind.Unspecified).AddTicks(9002), new TimeSpan(0, -5, 0, 0, 0)),
                            AddUser = "Seed",
                            DelFlag = false,
                            Label = "Lincoln Center"
                        });
                });

            modelBuilder.Entity("FHHL.Data.DomainModels.RiskLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityColumn();

                    b.Property<bool>("ActiveFlag")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("AddDateTimeOffset")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("AddUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset?>("ChgDateTimeOffset")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("ChgUser")
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset?>("DelDateTimeOffset")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<bool>("DelFlag")
                        .HasColumnType("bit");

                    b.Property<string>("DelUser")
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.ToTable("RiskLevels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActiveFlag = true,
                            AddDateTimeOffset = new DateTimeOffset(new DateTime(2021, 3, 16, 13, 16, 48, 531, DateTimeKind.Unspecified).AddTicks(9957), new TimeSpan(0, -5, 0, 0, 0)),
                            AddUser = "Seed",
                            DelFlag = false,
                            Label = "High"
                        },
                        new
                        {
                            Id = 2,
                            ActiveFlag = true,
                            AddDateTimeOffset = new DateTimeOffset(new DateTime(2021, 3, 16, 13, 16, 48, 532, DateTimeKind.Unspecified).AddTicks(1039), new TimeSpan(0, -5, 0, 0, 0)),
                            AddUser = "Seed",
                            DelFlag = false,
                            Label = "Medium"
                        },
                        new
                        {
                            Id = 3,
                            ActiveFlag = true,
                            AddDateTimeOffset = new DateTimeOffset(new DateTime(2021, 3, 16, 13, 16, 48, 532, DateTimeKind.Unspecified).AddTicks(1076), new TimeSpan(0, -5, 0, 0, 0)),
                            AddUser = "Seed",
                            DelFlag = false,
                            Label = "Low"
                        });
                });

            modelBuilder.Entity("FHHL.Data.DomainModels.VisitResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityColumn();

                    b.Property<bool>("ActiveFlag")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("AddDateTimeOffset")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("AddUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset?>("ChgDateTimeOffset")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("ChgUser")
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset?>("DelDateTimeOffset")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<bool>("DelFlag")
                        .HasColumnType("bit");

                    b.Property<string>("DelUser")
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.ToTable("VisitResults");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActiveFlag = true,
                            AddDateTimeOffset = new DateTimeOffset(new DateTime(2021, 3, 16, 13, 16, 48, 532, DateTimeKind.Unspecified).AddTicks(2044), new TimeSpan(0, -5, 0, 0, 0)),
                            AddUser = "Seed",
                            DelFlag = false,
                            Label = "Home Visit"
                        },
                        new
                        {
                            Id = 2,
                            ActiveFlag = true,
                            AddDateTimeOffset = new DateTimeOffset(new DateTime(2021, 3, 16, 13, 16, 48, 532, DateTimeKind.Unspecified).AddTicks(3129), new TimeSpan(0, -5, 0, 0, 0)),
                            AddUser = "Seed",
                            DelFlag = false,
                            Label = "Declined"
                        },
                        new
                        {
                            Id = 3,
                            ActiveFlag = true,
                            AddDateTimeOffset = new DateTimeOffset(new DateTime(2021, 3, 16, 13, 16, 48, 532, DateTimeKind.Unspecified).AddTicks(3170), new TimeSpan(0, -5, 0, 0, 0)),
                            AddUser = "Seed",
                            DelFlag = false,
                            Label = "No Response"
                        },
                        new
                        {
                            Id = 4,
                            ActiveFlag = true,
                            AddDateTimeOffset = new DateTimeOffset(new DateTime(2021, 3, 16, 13, 16, 48, 532, DateTimeKind.Unspecified).AddTicks(3177), new TimeSpan(0, -5, 0, 0, 0)),
                            AddUser = "Seed",
                            DelFlag = false,
                            Label = "Failed"
                        },
                        new
                        {
                            Id = 5,
                            ActiveFlag = true,
                            AddDateTimeOffset = new DateTimeOffset(new DateTime(2021, 3, 16, 13, 16, 48, 532, DateTimeKind.Unspecified).AddTicks(3183), new TimeSpan(0, -5, 0, 0, 0)),
                            AddUser = "Seed",
                            DelFlag = false,
                            Label = "Miscarried"
                        },
                        new
                        {
                            Id = 6,
                            ActiveFlag = true,
                            AddDateTimeOffset = new DateTimeOffset(new DateTime(2021, 3, 16, 13, 16, 48, 532, DateTimeKind.Unspecified).AddTicks(3189), new TimeSpan(0, -5, 0, 0, 0)),
                            AddUser = "Seed",
                            DelFlag = false,
                            Label = "Moved"
                        },
                        new
                        {
                            Id = 7,
                            ActiveFlag = true,
                            AddDateTimeOffset = new DateTimeOffset(new DateTime(2021, 3, 16, 13, 16, 48, 532, DateTimeKind.Unspecified).AddTicks(3195), new TimeSpan(0, -5, 0, 0, 0)),
                            AddUser = "Seed",
                            DelFlag = false,
                            Label = "Lost"
                        },
                        new
                        {
                            Id = 8,
                            ActiveFlag = true,
                            AddDateTimeOffset = new DateTimeOffset(new DateTime(2021, 3, 16, 13, 16, 48, 532, DateTimeKind.Unspecified).AddTicks(3201), new TimeSpan(0, -5, 0, 0, 0)),
                            AddUser = "Seed",
                            DelFlag = false,
                            Label = "Deferred"
                        },
                        new
                        {
                            Id = 9,
                            ActiveFlag = true,
                            AddDateTimeOffset = new DateTimeOffset(new DateTime(2021, 3, 16, 13, 16, 48, 532, DateTimeKind.Unspecified).AddTicks(3208), new TimeSpan(0, -5, 0, 0, 0)),
                            AddUser = "Seed",
                            DelFlag = false,
                            Label = "Enrolled"
                        },
                        new
                        {
                            Id = 10,
                            ActiveFlag = true,
                            AddDateTimeOffset = new DateTimeOffset(new DateTime(2021, 3, 16, 13, 16, 48, 532, DateTimeKind.Unspecified).AddTicks(3214), new TimeSpan(0, -5, 0, 0, 0)),
                            AddUser = "Seed",
                            DelFlag = false,
                            Label = "Other"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
