// <auto-generated />
using System;
using FHHL.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FHHL.Data.Migrations
{
    [DbContext(typeof(FHHLDbContext))]
    [Migration("20210114210110_jesse2")]
    partial class jesse2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("FHHL.Data.DomainModels.Assignee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityColumn();

                    b.Property<bool>("ActiveFlag")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("AddDateTimeOffset")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("AddUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset?>("ChgDateTimeOffset")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("ChgUser")
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset?>("DelDateTimeOffset")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<bool>("DelFlag")
                        .HasColumnType("bit");

                    b.Property<string>("DelUser")
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.ToTable("Assignees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActiveFlag = true,
                            AddDateTimeOffset = new DateTimeOffset(new DateTime(2021, 1, 14, 15, 1, 9, 667, DateTimeKind.Unspecified).AddTicks(9368), new TimeSpan(0, -6, 0, 0, 0)),
                            AddUser = "Seed",
                            DelFlag = false,
                            Label = "Teresa"
                        },
                        new
                        {
                            Id = 2,
                            ActiveFlag = true,
                            AddDateTimeOffset = new DateTimeOffset(new DateTime(2021, 1, 14, 15, 1, 9, 671, DateTimeKind.Unspecified).AddTicks(4088), new TimeSpan(0, -6, 0, 0, 0)),
                            AddUser = "Seed",
                            DelFlag = false,
                            Label = "Bonnie"
                        },
                        new
                        {
                            Id = 3,
                            ActiveFlag = true,
                            AddDateTimeOffset = new DateTimeOffset(new DateTime(2021, 1, 14, 15, 1, 9, 671, DateTimeKind.Unspecified).AddTicks(4156), new TimeSpan(0, -6, 0, 0, 0)),
                            AddUser = "Seed",
                            DelFlag = false,
                            Label = "Missy"
                        },
                        new
                        {
                            Id = 4,
                            ActiveFlag = true,
                            AddDateTimeOffset = new DateTimeOffset(new DateTime(2021, 1, 14, 15, 1, 9, 671, DateTimeKind.Unspecified).AddTicks(4164), new TimeSpan(0, -6, 0, 0, 0)),
                            AddUser = "Seed",
                            DelFlag = false,
                            Label = "Marla"
                        },
                        new
                        {
                            Id = 5,
                            ActiveFlag = true,
                            AddDateTimeOffset = new DateTimeOffset(new DateTime(2021, 1, 14, 15, 1, 9, 671, DateTimeKind.Unspecified).AddTicks(4168), new TimeSpan(0, -6, 0, 0, 0)),
                            AddUser = "Seed",
                            DelFlag = false,
                            Label = "Ariona"
                        },
                        new
                        {
                            Id = 6,
                            ActiveFlag = true,
                            AddDateTimeOffset = new DateTimeOffset(new DateTime(2021, 1, 14, 15, 1, 9, 671, DateTimeKind.Unspecified).AddTicks(4172), new TimeSpan(0, -6, 0, 0, 0)),
                            AddUser = "Seed",
                            DelFlag = false,
                            Label = "Outreach Letter"
                        },
                        new
                        {
                            Id = 7,
                            ActiveFlag = true,
                            AddDateTimeOffset = new DateTimeOffset(new DateTime(2021, 1, 14, 15, 1, 9, 671, DateTimeKind.Unspecified).AddTicks(4176), new TimeSpan(0, -6, 0, 0, 0)),
                            AddUser = "Seed",
                            DelFlag = false,
                            Label = "Felica"
                        },
                        new
                        {
                            Id = 8,
                            ActiveFlag = true,
                            AddDateTimeOffset = new DateTimeOffset(new DateTime(2021, 1, 14, 15, 1, 9, 671, DateTimeKind.Unspecified).AddTicks(4181), new TimeSpan(0, -6, 0, 0, 0)),
                            AddUser = "Seed",
                            DelFlag = false,
                            Label = "Jene"
                        },
                        new
                        {
                            Id = 9,
                            ActiveFlag = true,
                            AddDateTimeOffset = new DateTimeOffset(new DateTime(2021, 1, 14, 15, 1, 9, 671, DateTimeKind.Unspecified).AddTicks(4185), new TimeSpan(0, -6, 0, 0, 0)),
                            AddUser = "Seed",
                            DelFlag = false,
                            Label = "Abby"
                        },
                        new
                        {
                            Id = 10,
                            ActiveFlag = true,
                            AddDateTimeOffset = new DateTimeOffset(new DateTime(2021, 1, 14, 15, 1, 9, 671, DateTimeKind.Unspecified).AddTicks(4189), new TimeSpan(0, -6, 0, 0, 0)),
                            AddUser = "Seed",
                            DelFlag = false,
                            Label = "Tandem"
                        },
                        new
                        {
                            Id = 11,
                            ActiveFlag = true,
                            AddDateTimeOffset = new DateTimeOffset(new DateTime(2021, 1, 14, 15, 1, 9, 671, DateTimeKind.Unspecified).AddTicks(4193), new TimeSpan(0, -6, 0, 0, 0)),
                            AddUser = "Seed",
                            DelFlag = false,
                            Label = "Renee"
                        },
                        new
                        {
                            Id = 12,
                            ActiveFlag = true,
                            AddDateTimeOffset = new DateTimeOffset(new DateTime(2021, 1, 14, 15, 1, 9, 671, DateTimeKind.Unspecified).AddTicks(4198), new TimeSpan(0, -6, 0, 0, 0)),
                            AddUser = "Seed",
                            DelFlag = false,
                            Label = "Emma"
                        },
                        new
                        {
                            Id = 13,
                            ActiveFlag = true,
                            AddDateTimeOffset = new DateTimeOffset(new DateTime(2021, 1, 14, 15, 1, 9, 671, DateTimeKind.Unspecified).AddTicks(4202), new TimeSpan(0, -6, 0, 0, 0)),
                            AddUser = "Seed",
                            DelFlag = false,
                            Label = "Marsue"
                        });
                });

            modelBuilder.Entity("FHHL.Data.DomainModels.PregnancyState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityColumn();

                    b.Property<bool>("ActiveFlag")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("AddDateTimeOffset")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("AddUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset?>("ChgDateTimeOffset")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("ChgUser")
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset?>("DelDateTimeOffset")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<bool>("DelFlag")
                        .HasColumnType("bit");

                    b.Property<string>("DelUser")
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.ToTable("PregnancyStates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActiveFlag = true,
                            AddDateTimeOffset = new DateTimeOffset(new DateTime(2021, 1, 14, 15, 1, 9, 672, DateTimeKind.Unspecified).AddTicks(5634), new TimeSpan(0, -6, 0, 0, 0)),
                            AddUser = "Seed",
                            DelFlag = false,
                            Label = "Prebirth"
                        },
                        new
                        {
                            Id = 2,
                            ActiveFlag = true,
                            AddDateTimeOffset = new DateTimeOffset(new DateTime(2021, 1, 14, 15, 1, 9, 672, DateTimeKind.Unspecified).AddTicks(6892), new TimeSpan(0, -6, 0, 0, 0)),
                            AddUser = "Seed",
                            DelFlag = false,
                            Label = "Birth"
                        },
                        new
                        {
                            Id = 3,
                            ActiveFlag = true,
                            AddDateTimeOffset = new DateTimeOffset(new DateTime(2021, 1, 14, 15, 1, 9, 672, DateTimeKind.Unspecified).AddTicks(6942), new TimeSpan(0, -6, 0, 0, 0)),
                            AddUser = "Seed",
                            DelFlag = false,
                            Label = "Toddler"
                        },
                        new
                        {
                            Id = 4,
                            ActiveFlag = true,
                            AddDateTimeOffset = new DateTimeOffset(new DateTime(2021, 1, 14, 15, 1, 9, 672, DateTimeKind.Unspecified).AddTicks(6948), new TimeSpan(0, -6, 0, 0, 0)),
                            AddUser = "Seed",
                            DelFlag = false,
                            Label = "Infant"
                        },
                        new
                        {
                            Id = 5,
                            ActiveFlag = true,
                            AddDateTimeOffset = new DateTimeOffset(new DateTime(2021, 1, 14, 15, 1, 9, 672, DateTimeKind.Unspecified).AddTicks(6983), new TimeSpan(0, -6, 0, 0, 0)),
                            AddUser = "Seed",
                            DelFlag = false,
                            Label = "Postpartum"
                        });
                });

            modelBuilder.Entity("FHHL.Data.DomainModels.Program", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityColumn();

                    b.Property<bool>("ActiveFlag")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("AddDateTimeOffset")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("AddUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset?>("ChgDateTimeOffset")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("ChgUser")
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset?>("DelDateTimeOffset")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<bool>("DelFlag")
                        .HasColumnType("bit");

                    b.Property<string>("DelUser")
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.ToTable("Programs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActiveFlag = true,
                            AddDateTimeOffset = new DateTimeOffset(new DateTime(2021, 1, 14, 15, 1, 9, 672, DateTimeKind.Unspecified).AddTicks(8068), new TimeSpan(0, -6, 0, 0, 0)),
                            AddUser = "Seed",
                            DelFlag = false,
                            Label = "HSHV"
                        },
                        new
                        {
                            Id = 2,
                            ActiveFlag = true,
                            AddDateTimeOffset = new DateTimeOffset(new DateTime(2021, 1, 14, 15, 1, 9, 672, DateTimeKind.Unspecified).AddTicks(9122), new TimeSpan(0, -6, 0, 0, 0)),
                            AddUser = "Seed",
                            DelFlag = false,
                            Label = "NBHV"
                        },
                        new
                        {
                            Id = 3,
                            ActiveFlag = true,
                            AddDateTimeOffset = new DateTimeOffset(new DateTime(2021, 1, 14, 15, 1, 9, 672, DateTimeKind.Unspecified).AddTicks(9169), new TimeSpan(0, -6, 0, 0, 0)),
                            AddUser = "Seed",
                            DelFlag = false,
                            Label = "NFP"
                        },
                        new
                        {
                            Id = 4,
                            ActiveFlag = true,
                            AddDateTimeOffset = new DateTimeOffset(new DateTime(2021, 1, 14, 15, 1, 9, 672, DateTimeKind.Unspecified).AddTicks(9175), new TimeSpan(0, -6, 0, 0, 0)),
                            AddUser = "Seed",
                            DelFlag = false,
                            Label = "PHN"
                        },
                        new
                        {
                            Id = 5,
                            ActiveFlag = true,
                            AddDateTimeOffset = new DateTimeOffset(new DateTime(2021, 1, 14, 15, 1, 9, 672, DateTimeKind.Unspecified).AddTicks(9180), new TimeSpan(0, -6, 0, 0, 0)),
                            AddUser = "Seed",
                            DelFlag = false,
                            Label = "PART C"
                        },
                        new
                        {
                            Id = 6,
                            ActiveFlag = true,
                            AddDateTimeOffset = new DateTimeOffset(new DateTime(2021, 1, 14, 15, 1, 9, 672, DateTimeKind.Unspecified).AddTicks(9184), new TimeSpan(0, -6, 0, 0, 0)),
                            AddUser = "Seed",
                            DelFlag = false,
                            Label = "FS"
                        },
                        new
                        {
                            Id = 7,
                            ActiveFlag = true,
                            AddDateTimeOffset = new DateTimeOffset(new DateTime(2021, 1, 14, 15, 1, 9, 672, DateTimeKind.Unspecified).AddTicks(9188), new TimeSpan(0, -6, 0, 0, 0)),
                            AddUser = "Seed",
                            DelFlag = false,
                            Label = "Outreach"
                        });
                });

            modelBuilder.Entity("FHHL.Data.DomainModels.Race", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityColumn();

                    b.Property<bool>("ActiveFlag")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("AddDateTimeOffset")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("AddUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset?>("ChgDateTimeOffset")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("ChgUser")
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset?>("DelDateTimeOffset")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<bool>("DelFlag")
                        .HasColumnType("bit");

                    b.Property<string>("DelUser")
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.ToTable("Races");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActiveFlag = true,
                            AddDateTimeOffset = new DateTimeOffset(new DateTime(2021, 1, 14, 15, 1, 9, 673, DateTimeKind.Unspecified).AddTicks(91), new TimeSpan(0, -6, 0, 0, 0)),
                            AddUser = "Seed",
                            DelFlag = false,
                            Label = "White"
                        },
                        new
                        {
                            Id = 2,
                            ActiveFlag = true,
                            AddDateTimeOffset = new DateTimeOffset(new DateTime(2021, 1, 14, 15, 1, 9, 673, DateTimeKind.Unspecified).AddTicks(1134), new TimeSpan(0, -6, 0, 0, 0)),
                            AddUser = "Seed",
                            DelFlag = false,
                            Label = "Black"
                        },
                        new
                        {
                            Id = 3,
                            ActiveFlag = true,
                            AddDateTimeOffset = new DateTimeOffset(new DateTime(2021, 1, 14, 15, 1, 9, 673, DateTimeKind.Unspecified).AddTicks(1171), new TimeSpan(0, -6, 0, 0, 0)),
                            AddUser = "Seed",
                            DelFlag = false,
                            Label = "Black/White"
                        },
                        new
                        {
                            Id = 4,
                            ActiveFlag = true,
                            AddDateTimeOffset = new DateTimeOffset(new DateTime(2021, 1, 14, 15, 1, 9, 673, DateTimeKind.Unspecified).AddTicks(1176), new TimeSpan(0, -6, 0, 0, 0)),
                            AddUser = "Seed",
                            DelFlag = false,
                            Label = "American Indian"
                        },
                        new
                        {
                            Id = 5,
                            ActiveFlag = true,
                            AddDateTimeOffset = new DateTimeOffset(new DateTime(2021, 1, 14, 15, 1, 9, 673, DateTimeKind.Unspecified).AddTicks(1181), new TimeSpan(0, -6, 0, 0, 0)),
                            AddUser = "Seed",
                            DelFlag = false,
                            Label = "Asian"
                        },
                        new
                        {
                            Id = 6,
                            ActiveFlag = true,
                            AddDateTimeOffset = new DateTimeOffset(new DateTime(2021, 1, 14, 15, 1, 9, 673, DateTimeKind.Unspecified).AddTicks(1186), new TimeSpan(0, -6, 0, 0, 0)),
                            AddUser = "Seed",
                            DelFlag = false,
                            Label = "Non-Hispanic"
                        },
                        new
                        {
                            Id = 7,
                            ActiveFlag = true,
                            AddDateTimeOffset = new DateTimeOffset(new DateTime(2021, 1, 14, 15, 1, 9, 673, DateTimeKind.Unspecified).AddTicks(1190), new TimeSpan(0, -6, 0, 0, 0)),
                            AddUser = "Seed",
                            DelFlag = false,
                            Label = "Unknown"
                        },
                        new
                        {
                            Id = 8,
                            ActiveFlag = true,
                            AddDateTimeOffset = new DateTimeOffset(new DateTime(2021, 1, 14, 15, 1, 9, 673, DateTimeKind.Unspecified).AddTicks(1195), new TimeSpan(0, -6, 0, 0, 0)),
                            AddUser = "Seed",
                            DelFlag = false,
                            Label = "Other"
                        });
                });

            modelBuilder.Entity("FHHL.Data.DomainModels.ReferralSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityColumn();

                    b.Property<bool>("ActiveFlag")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("AddDateTimeOffset")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("AddUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset?>("ChgDateTimeOffset")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("ChgUser")
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset?>("DelDateTimeOffset")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<bool>("DelFlag")
                        .HasColumnType("bit");

                    b.Property<string>("DelUser")
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.ToTable("ReferralSources");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActiveFlag = true,
                            AddDateTimeOffset = new DateTimeOffset(new DateTime(2021, 1, 14, 15, 1, 9, 673, DateTimeKind.Unspecified).AddTicks(2119), new TimeSpan(0, -6, 0, 0, 0)),
                            AddUser = "Seed",
                            DelFlag = false,
                            Label = "PG Testing"
                        },
                        new
                        {
                            Id = 2,
                            ActiveFlag = true,
                            AddDateTimeOffset = new DateTimeOffset(new DateTime(2021, 1, 14, 15, 1, 9, 673, DateTimeKind.Unspecified).AddTicks(3237), new TimeSpan(0, -6, 0, 0, 0)),
                            AddUser = "Seed",
                            DelFlag = false,
                            Label = "M & I"
                        },
                        new
                        {
                            Id = 3,
                            ActiveFlag = true,
                            AddDateTimeOffset = new DateTimeOffset(new DateTime(2021, 1, 14, 15, 1, 9, 673, DateTimeKind.Unspecified).AddTicks(3281), new TimeSpan(0, -6, 0, 0, 0)),
                            AddUser = "Seed",
                            DelFlag = false,
                            Label = "Hopsital"
                        },
                        new
                        {
                            Id = 4,
                            ActiveFlag = true,
                            AddDateTimeOffset = new DateTimeOffset(new DateTime(2021, 1, 14, 15, 1, 9, 673, DateTimeKind.Unspecified).AddTicks(3286), new TimeSpan(0, -6, 0, 0, 0)),
                            AddUser = "Seed",
                            DelFlag = false,
                            Label = "WIC"
                        },
                        new
                        {
                            Id = 5,
                            ActiveFlag = true,
                            AddDateTimeOffset = new DateTimeOffset(new DateTime(2021, 1, 14, 15, 1, 9, 673, DateTimeKind.Unspecified).AddTicks(3291), new TimeSpan(0, -6, 0, 0, 0)),
                            AddUser = "Seed",
                            DelFlag = false,
                            Label = "Successful Connections"
                        },
                        new
                        {
                            Id = 6,
                            ActiveFlag = true,
                            AddDateTimeOffset = new DateTimeOffset(new DateTime(2021, 1, 14, 15, 1, 9, 673, DateTimeKind.Unspecified).AddTicks(3295), new TimeSpan(0, -6, 0, 0, 0)),
                            AddUser = "Seed",
                            DelFlag = false,
                            Label = "TARC"
                        },
                        new
                        {
                            Id = 7,
                            ActiveFlag = true,
                            AddDateTimeOffset = new DateTimeOffset(new DateTime(2021, 1, 14, 15, 1, 9, 673, DateTimeKind.Unspecified).AddTicks(3300), new TimeSpan(0, -6, 0, 0, 0)),
                            AddUser = "Seed",
                            DelFlag = false,
                            Label = "Washburn"
                        },
                        new
                        {
                            Id = 8,
                            ActiveFlag = true,
                            AddDateTimeOffset = new DateTimeOffset(new DateTime(2021, 1, 14, 15, 1, 9, 673, DateTimeKind.Unspecified).AddTicks(3304), new TimeSpan(0, -6, 0, 0, 0)),
                            AddUser = "Seed",
                            DelFlag = false,
                            Label = "Other"
                        },
                        new
                        {
                            Id = 9,
                            ActiveFlag = true,
                            AddDateTimeOffset = new DateTimeOffset(new DateTime(2021, 1, 14, 15, 1, 9, 673, DateTimeKind.Unspecified).AddTicks(3308), new TimeSpan(0, -6, 0, 0, 0)),
                            AddUser = "Seed",
                            DelFlag = false,
                            Label = "Lincoln Center"
                        });
                });

            modelBuilder.Entity("FHHL.Data.DomainModels.RiskLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityColumn();

                    b.Property<bool>("ActiveFlag")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("AddDateTimeOffset")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("AddUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset?>("ChgDateTimeOffset")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("ChgUser")
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset?>("DelDateTimeOffset")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<bool>("DelFlag")
                        .HasColumnType("bit");

                    b.Property<string>("DelUser")
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.ToTable("RiskLevels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActiveFlag = true,
                            AddDateTimeOffset = new DateTimeOffset(new DateTime(2021, 1, 14, 15, 1, 9, 673, DateTimeKind.Unspecified).AddTicks(4171), new TimeSpan(0, -6, 0, 0, 0)),
                            AddUser = "Seed",
                            DelFlag = false,
                            Label = "High"
                        },
                        new
                        {
                            Id = 2,
                            ActiveFlag = true,
                            AddDateTimeOffset = new DateTimeOffset(new DateTime(2021, 1, 14, 15, 1, 9, 673, DateTimeKind.Unspecified).AddTicks(5166), new TimeSpan(0, -6, 0, 0, 0)),
                            AddUser = "Seed",
                            DelFlag = false,
                            Label = "Medium"
                        },
                        new
                        {
                            Id = 3,
                            ActiveFlag = true,
                            AddDateTimeOffset = new DateTimeOffset(new DateTime(2021, 1, 14, 15, 1, 9, 673, DateTimeKind.Unspecified).AddTicks(5202), new TimeSpan(0, -6, 0, 0, 0)),
                            AddUser = "Seed",
                            DelFlag = false,
                            Label = "Low"
                        });
                });

            modelBuilder.Entity("FHHL.Data.DomainModels.VisitResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityColumn();

                    b.Property<bool>("ActiveFlag")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("AddDateTimeOffset")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("AddUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset?>("ChgDateTimeOffset")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("ChgUser")
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset?>("DelDateTimeOffset")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<bool>("DelFlag")
                        .HasColumnType("bit");

                    b.Property<string>("DelUser")
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.ToTable("VisitResults");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActiveFlag = true,
                            AddDateTimeOffset = new DateTimeOffset(new DateTime(2021, 1, 14, 15, 1, 9, 673, DateTimeKind.Unspecified).AddTicks(6057), new TimeSpan(0, -6, 0, 0, 0)),
                            AddUser = "Seed",
                            DelFlag = false,
                            Label = "Home Visit"
                        },
                        new
                        {
                            Id = 2,
                            ActiveFlag = true,
                            AddDateTimeOffset = new DateTimeOffset(new DateTime(2021, 1, 14, 15, 1, 9, 673, DateTimeKind.Unspecified).AddTicks(7045), new TimeSpan(0, -6, 0, 0, 0)),
                            AddUser = "Seed",
                            DelFlag = false,
                            Label = "Declined"
                        },
                        new
                        {
                            Id = 3,
                            ActiveFlag = true,
                            AddDateTimeOffset = new DateTimeOffset(new DateTime(2021, 1, 14, 15, 1, 9, 673, DateTimeKind.Unspecified).AddTicks(7083), new TimeSpan(0, -6, 0, 0, 0)),
                            AddUser = "Seed",
                            DelFlag = false,
                            Label = "No Response"
                        },
                        new
                        {
                            Id = 4,
                            ActiveFlag = true,
                            AddDateTimeOffset = new DateTimeOffset(new DateTime(2021, 1, 14, 15, 1, 9, 673, DateTimeKind.Unspecified).AddTicks(7088), new TimeSpan(0, -6, 0, 0, 0)),
                            AddUser = "Seed",
                            DelFlag = false,
                            Label = "Failed"
                        },
                        new
                        {
                            Id = 5,
                            ActiveFlag = true,
                            AddDateTimeOffset = new DateTimeOffset(new DateTime(2021, 1, 14, 15, 1, 9, 673, DateTimeKind.Unspecified).AddTicks(7093), new TimeSpan(0, -6, 0, 0, 0)),
                            AddUser = "Seed",
                            DelFlag = false,
                            Label = "Miscarried"
                        },
                        new
                        {
                            Id = 6,
                            ActiveFlag = true,
                            AddDateTimeOffset = new DateTimeOffset(new DateTime(2021, 1, 14, 15, 1, 9, 673, DateTimeKind.Unspecified).AddTicks(7097), new TimeSpan(0, -6, 0, 0, 0)),
                            AddUser = "Seed",
                            DelFlag = false,
                            Label = "Moved"
                        },
                        new
                        {
                            Id = 7,
                            ActiveFlag = true,
                            AddDateTimeOffset = new DateTimeOffset(new DateTime(2021, 1, 14, 15, 1, 9, 673, DateTimeKind.Unspecified).AddTicks(7101), new TimeSpan(0, -6, 0, 0, 0)),
                            AddUser = "Seed",
                            DelFlag = false,
                            Label = "Lost"
                        },
                        new
                        {
                            Id = 8,
                            ActiveFlag = true,
                            AddDateTimeOffset = new DateTimeOffset(new DateTime(2021, 1, 14, 15, 1, 9, 673, DateTimeKind.Unspecified).AddTicks(7106), new TimeSpan(0, -6, 0, 0, 0)),
                            AddUser = "Seed",
                            DelFlag = false,
                            Label = "Deferred"
                        },
                        new
                        {
                            Id = 9,
                            ActiveFlag = true,
                            AddDateTimeOffset = new DateTimeOffset(new DateTime(2021, 1, 14, 15, 1, 9, 673, DateTimeKind.Unspecified).AddTicks(7110), new TimeSpan(0, -6, 0, 0, 0)),
                            AddUser = "Seed",
                            DelFlag = false,
                            Label = "Enrolled"
                        },
                        new
                        {
                            Id = 10,
                            ActiveFlag = true,
                            AddDateTimeOffset = new DateTimeOffset(new DateTime(2021, 1, 14, 15, 1, 9, 673, DateTimeKind.Unspecified).AddTicks(7114), new TimeSpan(0, -6, 0, 0, 0)),
                            AddUser = "Seed",
                            DelFlag = false,
                            Label = "Other"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
