# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: with cache

on:
  workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Cache dotnet
      id: cache-dotnet-core
      uses: actions/cache@v3
      with:
        path: '~/usr/share/dotnet'
        key: ${{ runner.os }}-dotnet-3-1   
    
    - name: Setup .NET
      if: steps.cache-dotnet-core.outputs.cache-hit != 'true'
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 3.1.x
                
    - name: Restore dependencies
      run: dotnet restore FHHL/FHHL.sln
      
    - name: Build
      run: dotnet build FHHL/FHHL/FHHL.Web.csproj --no-restore

