# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: builds artifact

on:
  pull_request:
    branches:
      -main
    

jobs:
  build-publish-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '3.1.x'


      - name: Build and publish projects
        run: |
          for project in $(find . -name '*.csproj'); do
            project_dir=$(dirname $project)
            project_name=$(basename $project .csproj)
            output_dir="$project_dir/bin/Release/netcoreapp3.1/publish"
            dotnet publish $project --configuration Release --output $output_dir
          done
          
      - name: Check for Changes
        uses: dorny/paths-filter@v2
        id: filter
        with: 
          filters: |
            CommonService:
              - 'FHHL/Common.Service/**'
            CommonWeb:
              - 'FHHL/Common.Web/**'
            FHHLData:
              - 'FHHL/FHHL.Data/**'
            FHHLBLL:
              - 'FHHL/FHHL.BLL/**'
            FHHL:
              - 'FHHL/FHHL/**'
      
      - name: Upload Common.Service Artifact
        if: steps.filter.outputs.CommonService == 'true'
        uses: actions/upload-artifact@v2
        with:
          name: Common.Service
          path: ./FHHL/Common.Service/bin/Release/netcoreapp3.1/publish
          
      - name: Upload Common.Web Artifact
        if: steps.filter.outputs.CommonWeb == 'true'
        uses: actions/upload-artifact@v2
        with:
          name: Common.Web
          path: ./FHHL/Common.Web/bin/Release/netcoreapp3.1/publish
          
      - name: Upload FHHL.Data Artifact
        if: steps.filter.outputs.FHHLData == 'true'
        uses: actions/upload-artifact@v2
        with:
          name: FHHL.Data
          path: ./FHHL/FHHL.Data/bin/Release/netcoreapp3.1/publish
          
      - name: Upload FHHL.BLL Artifact
        if: steps.filter.outputs.FHHLBLL == 'true'
        uses: actions/upload-artifact@v2
        with:
          name: FHHL.BLL
          path: ./FHHL/FHHL.BLL/bin/Release/netcoreapp3.1/publish
          
      - name: Upload FHHL Artifact
        if: steps.filter.outputs.FHHL == 'true'
        uses: actions/upload-artifact@v2
        with:
          name: FHHL
          path: ./FHHL/FHHL/bin/Release/netcoreapp3.1/publish

