# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: builds artifact

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  restore-build-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Display Current Directory
        run: pwd

      - name: Display Directory Files
        run: ls -la
    
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '3.1.x'

      - name: Cache .NET Core dependencies
        id: cache
        uses: actions/cache@v2
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-dotnet-packages-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-dotnet-packages-

      - name: Restore dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: dotnet restore ./FHHL/FHHL/FHHL.Web.csproj

      - name: Build
        run: dotnet build ./FHHL/FHHL/FHHL.Web.csproj --configuration Release --no-restore  
                
      - name: Upload FHHL Artifact
        if: steps.filter.outputs.FHHL == 'true'
        uses: actions/upload-artifact@v2
        with:
          name: FHHL
          path: ./FHHL/FHHL/bin/Release/netcoreapp3.1/publish

  deploy:
    needs: restore-build-publish
    runs-on: ubuntu-latest
    steps:
      - uses: azure/pipelines@v2
        with:
          project: Test-FHHL 
          pipeline: On GitHub Release - Deploy
          token: ${{ secrets.AZURE_DEVOPS_TOKEN }}
          artifact: FHHL

