# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: builds artifact

on:
  workflow_dispatch

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.x' # Choose the appropriate .NET Core version

      - name: Debug Output Directory
        run: |
          ls -R ${{ github.workspace }}/${{ steps.build-and-publish.outputs.project }}/bin/Release/netcoreapp3.1/publish

      - name: Build and publish projects
        run: |
          for project in $(find . -name '*.csproj'); do
            project_dir=$(dirname $project)
            project_name=$(basename $project .csproj)
            output_dir="$project_dir/bin/Release/netcoreapp3.1/publish"
            
            dotnet publish $project --configuration Release --output $output_dir
            
            # Set the project name as an output variable
            echo "::set-output name=project::$project_name"
          done

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.build-and-publish.outputs.project }}
          path: ${{ steps.build-and-publish.outputs.project }}/bin/Release/netcoreapp3.1/publish

