# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: builds artifact

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  restore-build-publish:
    runs-on: ubuntu-latest

    steps:  
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '3.1.x'
          
      - name: Restore dependencies
        run: dotnet restore ./FHHL/FHHL/FHHL.Web.csproj

      - name: Build
        run: dotnet build ./FHHL/FHHL/FHHL.Web.csproj --configuration Release --no-restore  

      - name: Display Files
        run: |
          ls
          ls ./FHHL
          ls ./FHHL/bin
          ls ./FHHL/bin/Release
          ls ./FHHL/bin/Release/netcoreapp3.1
                
      - name: Upload FHHL Artifact
        uses: actions/upload-artifact@v2
        with:
          name: FHHL
          path: ./FHHL/FHHL/bin/Release/netcoreapp3.1/publish

  deploy:
    needs: restore-build-publish
    runs-on: ubuntu-latest
    steps:
      - uses: azure/pipelines@v1
        with:
          azure-devops-project-url: https://dev.azure.com/jessbrox809/Test-FHHL
          azure-pipeline-name: On GitHub Release - Deploy
          azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}

